### ISSUE TITLE
Change the toolbox icon on keyboard

### ISSUE THREAD

**Issue by Zezombye** [numworks/dieter#1]
[This icon](https://puu.sh/xnXXx.jpg) is supposed to be a toolbox. However it also looks like a printer icon, which is what I and jacobly0 thought it was (and probably many others).

If you want to keep the toolbox, angling the edges like [this](http://puu.sh/xnY1T.jpg) should be enough to not mistake the handle for a sheed of paper.

However, since you've mentioned you base your design on smartphones, why not use [the menu icon from android](https://i.stack.imgur.com/Fw96Z.png)? It would be more recognizable.

**Comment by artaxxx** [comment]
That's a good point!

Our designer worked on this issue and drew a new icon. 

What do you think about that suggestion?

![toolbox](https://user-images.githubusercontent.com/20040032/29928202-ad076d9e-8e68-11e7-9cba-1c28d311a295.png)

**Comment by Zezombye** [comment]
Looks more like a hamburger with a handle TBH :p
The lock should be closer to the top, like this: https://cdn.pixabay.com/photo/2013/07/12/17/38/toolbox-152140_960_720.png also angle the handle, because it still looks like paper, and therefore could still be mistaken for a printer. The lock should also be a horizontal rectangle, not vertical.

But well, I think the menu icon is the best, it's way more recognizable.

**Comment by adriweb** [comment]
Better indeed, but I agree with @Zezombye's suggestions

**Comment by adriweb** [comment]
This can be closed, it's done now :)
https://github.com/numworks/epsilon/pull/582/commits/de841bb73b8b74370f219a210cff93871a9f1072?short_path=726f09b#diff-726f09b4dca457c4f4672fcf19036996

**Comment by Ecco** [comment]
Good catch 😃
