### ISSUE TITLE
n0110 STLs

### ISSUE THREAD

**Issue by gkelly** [numworks/dieter#12]
The existing STLs appear to be for the n0100.  When I printed `top.stl` it doesn't mate with the n0110 bottom case.  It appears that there are some structural changes, such as the stiffeners, that aren't compatible.

The `top.stl` print compared to the n0110 top, showing the different placement of the stiffeners:
![IMG_20200123_211942](https://user-images.githubusercontent.com/48158/73040135-6e64ca80-3e26-11ea-95db-a62d7bab88ea.jpg)

The `top.stl` print compared to the n0110 bottom, showing the slots for the stiffeners not matching:
![IMG_20200123_212502](https://user-images.githubusercontent.com/48158/73040346-3ad67000-3e27-11ea-8749-01183d6a99b5.jpg)

Would you be willing to release the n0110 STLs?

**Comment by eried** [comment]
That's a sweet translucent case for the calculator BTW!

**Comment by gkelly** [comment]
> That's a sweet translucent case for the calculator BTW!

I was trying to spice up my n0110, trying out the front case for fit before running the back as well.  The light pipe for the LEDs would look really nice through a translucent case, I think.

**Comment by M4xi1m3** [comment]
Totally agree. N0110 STLs would be really nice to have, especially for people with a 3D printer willing to do custom stuff.

**Comment by artaxxx** [comment]
We've just uploaded the STLs!
