### ISSUE TITLE
Older versions of STL lending out. 

### ISSUE THREAD

**Issue by moorlag** [numworks/dieter#13]
Am I correct to assume that the files provided here (as is) are only for the newest release of the calculator? 
I want to tweak my 'old' calculator so I can lend it out to students (I was thinking of a magenta/pink version for lending). 

Could you publish the older version?

**Comment by eried** [comment]
The point of git is that you can go back in time, check "Commits" to find the version you want

**Comment by Ecco** [comment]
Indeed, the previous versions are in the commit history! I'm going to close this issue 😄
