### ISSUE TITLE
Keyboard colour scheme is hard to read

### ISSUE THREAD

**Issue by ian-abbott** [numworks/dieter#5]
There! I've said it! I can barely see most of the orange and light grey characters on the keyboard, both on the real device and on the online simulator.

**Comment by itamblyn** [comment]
Same issue, especially the orange. A different shade would help with usability and accessibility.

**Comment by ChuckM** [comment]
This is a challenge and I came to file an issue here. Just got mine and yellow is especially hard. Way too close to the 'white' chroma. Dark green, dark blue, or dark orange would be a better fit here. I realize you probably don't want to run into color blindness issues which always going to be challenging but there are some good three color combos that will let you maintain contrast and distinctiveness.

**Comment by eried** [comment]
Yes! +1

Please sell a button replacement kit with darker colors

**Comment by adriweb** [comment]
This can be closed, it's been updated for better readability now :)
https://github.com/numworks/epsilon/pull/582/commits/de841bb73b8b74370f219a210cff93871a9f1072?short_path=726f09b#diff-726f09b4dca457c4f4672fcf19036996

(Available after this summer, see latest NumLetter)

**Comment by Ecco** [comment]
Indeed 😄

**Comment by eried** [comment]
... but, can we buy the new scheme for replacing ours?

**Comment by adriweb** [comment]
Someone asked the same question [on tiplanet](https://tiplanet.org/forum/viewtopic.php?f=97&t=21664) ^^

**Comment by eried** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/1091420/41898414-4619e082-792a-11e8-9390-96c2e26e01f7.png)

but _frenchier_ 🍟
