### ISSUE TITLE
Calculator should calculate

### ISSUE THREAD

**Issue by ChuckM** [numworks/dieter#7]
I love the flexibility here but the thing is first and foremost a calculator. Ideally if you click it 'on' it should be ready to calculate. It is great that it will stay in the calculator app if you turn off and then on while you are in the calculator app, but I would really appreciate a setting that *always* brought it up in calculate if it wasn't in some other app before. That will probably be my first PR.

**Comment by Ecco** [comment]
Hi again @ChuckM. Same comment as #9 : please move to https://github.com/numworks/epsilon/issues (I can't do it on your behalf).

**Comment by ChuckM** [comment]
Moved to Epsilon
