### ISSUE TITLE
Font Size in Calculate is too small

### ISSUE THREAD

**Issue by ChuckM** [numworks/dieter#9]
I think it is great that you can see many lines of computation but for the calculate function I would really like a much larger font size. Look at existing calculators, digit sizes of 6mm vs the current 3mm would help readability a lot. Having it be adjustable would be even better.

**Comment by Ecco** [comment]
Hi @ChuckM ! Thanks for the feedback. Would you mind closing this issue and re-opening it on the "epsilon" repository? That's where we track bugs/enhancement for the software of the calculator. Thanks!

**Comment by ChuckM** [comment]
Moving to the Epsilon issue list.
